# Generated by Django 2.0.6 on 2019-03-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
